### ISSUE TITLE
Issue while installing cugraph package

### ISSUE THREAD

**Issue by waqar12868** [flandolfi/kplex-pool#6]
Hello!

Could you please help me setup the environment to run this package. I am trying to install following packages using conda mentioned in your repository but i am facing these issues:
conda install -y -c nvidia -c rapidsai -c numba -c conda-forge -c defaults \
      dask-cudf dask-cuda cugraph=0.15 cudatoolkit=10.1 c-compiler cxx-compiler

I received this error:

PackagesNotFoundError: The following packages are not available from current channels:

  - cugraph

I am waiting for your kind response.

Best Regards,

**Comment by flandolfi** [comment]
Hi,

I executed the commands in the README file, i.e.,
```
conda create -n kplex-pool python=3.7 -y
conda activate kplex-pool
conda install -y -c nvidia -c rapidsai -c numba -c conda-forge -c defaults \
      dask-cudf dask-cuda cugraph=0.15 cudatoolkit=10.1 c-compiler cxx-compiler
```
and it installs `cugraph` without any problem. My `conda` version is 4.9.2, but this should not be relevant at all. A quick check in the [`rapidsai` repository](https://anaconda.org/rapidsai/cugraph/files?page=2) shows that the version 0.15 of `cugraph`, although a bit outdated, is still there.

What is your OS? It seems that the RAPIDS suite is available only on Linux (Ubuntu/CentOS/RHEL), maybe that's the problem. See https://rapids.ai/start.html#get-rapids

Francesco

**Comment by waqar12868** [comment]
Thank you for your quick reply. 
I am using windows.

**Comment by flandolfi** [comment]
Then we found the problem. I don't think there's any way to get around this, sorry about that. Anyway, the `cugraph` package is used only in the `benchmark/` module, which is needed only for executing the experiments. You should be able to use the rest (i.e., anything in the `kplex_pool/` folder) without installing it!

**Comment by waqar12868** [comment]
Thank you for sharing this information. I am interested in the kplex_pool module. 
Again thanks for your quick response.

**Comment by flandolfi** [comment]
You're welcome! (I'll close this issue!)
