### ISSUE TITLE
After installation of each and every requirements (libraries) the setup.py file is not working. 

### ISSUE THREAD

**Issue by waqar12868** [flandolfi/kplex-pool#7]
After installation of the prerequisite (libraries) the setup.py file is not working. 
Here is the error in the code:

DistutilsArgError: no commands supplied

During handling of the above exception, another exception occurred:

SystemExit: usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: no commands supplied

please guide me about this error.
Thank you.

**Comment by flandolfi** [comment]
Hi again,

I executed these commands (essentially install everything but RAPIDS-related packages):
```
conda create -n test python=3.7 -y
conda activate test 
conda install -y -c conda-forge cudatoolkit=10.1 c-compiler cxx-compiler
pip install -r requirements.txt   
pip install .
```
and `kplex-pool` was installed correctly. The output of the last command is the following.
```
Processing /home/flandolfi/kplex-pool
  DEPRECATION: A future pip version will change local packages to be built in-place without first copying to a temporary directory. We recommend you use --use-feature=in-tree-build to test your packages with this new behavior before it becomes the default.
   pip 21.3 will remove support for this functionality. You can find discussion regarding this at https://github.com/pypa/pip/issues/7555.
Requirement already satisfied: numpy in /opt/anaconda3/envs/test/lib/python3.7/site-packages (from kplex-pool==0.0.1) (1.21.6)
Requirement already satisfied: torch in /opt/anaconda3/envs/test/lib/python3.7/site-packages (from kplex-pool==0.0.1) (1.7.0+cu101)
Requirement already satisfied: torch_cluster in /opt/anaconda3/envs/test/lib/python3.7/site-packages (from kplex-pool==0.0.1) (1.5.9)
Requirement already satisfied: torch_sparse in /opt/anaconda3/envs/test/lib/python3.7/site-packages (from kplex-pool==0.0.1) (0.6.9)
Requirement already satisfied: torch_geometric in /opt/anaconda3/envs/test/lib/python3.7/site-packages (from kplex-pool==0.0.1) (2.0.4)
Requirement already satisfied: tqdm in /opt/anaconda3/envs/test/lib/python3.7/site-packages (from kplex-pool==0.0.1) (4.64.0)
Requirement already satisfied: typing-extensions in /opt/anaconda3/envs/test/lib/python3.7/site-packages (from torch->kplex-pool==0.0.1) (4.2.0)
Requirement already satisfied: future in /opt/anaconda3/envs/test/lib/python3.7/site-packages (from torch->kplex-pool==0.0.1) (0.18.2)
Requirement already satisfied: dataclasses in /opt/anaconda3/envs/test/lib/python3.7/site-packages (from torch->kplex-pool==0.0.1) (0.6)
Requirement already satisfied: scikit-learn in /opt/anaconda3/envs/test/lib/python3.7/site-packages (from torch_geometric->kplex-pool==0.0.1) (1.0.2)
Requirement already satisfied: pandas in /opt/anaconda3/envs/test/lib/python3.7/site-packages (from torch_geometric->kplex-pool==0.0.1) (1.3.5)
Requirement already satisfied: pyparsing in /opt/anaconda3/envs/test/lib/python3.7/site-packages (from torch_geometric->kplex-pool==0.0.1) (3.0.8)
Requirement already satisfied: scipy in /opt/anaconda3/envs/test/lib/python3.7/site-packages (from torch_geometric->kplex-pool==0.0.1) (1.7.3)
Requirement already satisfied: jinja2 in /opt/anaconda3/envs/test/lib/python3.7/site-packages (from torch_geometric->kplex-pool==0.0.1) (3.1.1)
Requirement already satisfied: requests in /opt/anaconda3/envs/test/lib/python3.7/site-packages (from torch_geometric->kplex-pool==0.0.1) (2.27.1)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/anaconda3/envs/test/lib/python3.7/site-packages (from jinja2->torch_geometric->kplex-pool==0.0.1) (2.1.1)
Requirement already satisfied: pytz>=2017.3 in /opt/anaconda3/envs/test/lib/python3.7/site-packages (from pandas->torch_geometric->kplex-pool==0.0.1) (2022.1)
Requirement already satisfied: python-dateutil>=2.7.3 in /opt/anaconda3/envs/test/lib/python3.7/site-packages (from pandas->torch_geometric->kplex-pool==0.0.1) (2.8.2)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/envs/test/lib/python3.7/site-packages (from python-dateutil>=2.7.3->pandas->torch_geometric->kplex-pool==0.0.1) (1.16.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /opt/anaconda3/envs/test/lib/python3.7/site-packages (from requests->torch_geometric->kplex-pool==0.0.1) (1.26.9)
Requirement already satisfied: charset-normalizer~=2.0.0 in /opt/anaconda3/envs/test/lib/python3.7/site-packages (from requests->torch_geometric->kplex-pool==0.0.1) (2.0.12)
Requirement already satisfied: certifi>=2017.4.17 in /opt/anaconda3/envs/test/lib/python3.7/site-packages (from requests->torch_geometric->kplex-pool==0.0.1) (2021.10.8)
Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/envs/test/lib/python3.7/site-packages (from requests->torch_geometric->kplex-pool==0.0.1) (3.3)
Requirement already satisfied: threadpoolctl>=2.0.0 in /opt/anaconda3/envs/test/lib/python3.7/site-packages (from scikit-learn->torch_geometric->kplex-pool==0.0.1) (3.1.0)
Requirement already satisfied: joblib>=0.11 in /opt/anaconda3/envs/test/lib/python3.7/site-packages (from scikit-learn->torch_geometric->kplex-pool==0.0.1) (1.1.0)
Building wheels for collected packages: kplex-pool
  Building wheel for kplex-pool (setup.py) ... done
  Created wheel for kplex-pool: filename=kplex_pool-0.0.1-cp37-cp37m-linux_x86_64.whl size=334781 sha256=6a0cddb7de9896e79558d75fc7c52367e162de9f01dfd715dab132fb49f31f5d
  Stored in directory: /home/flandolfi/.cache/pip/wheels/02/df/0a/0477d043bd40014dfff2dd7eaa4e7a9c71f23ebd7d2485b27f
Successfully built kplex-pool
Installing collected packages: kplex-pool
Successfully installed kplex-pool-0.0.1
```

Which command(s) did you execute? Could you show me the full output?

Francesco

**Comment by waqar12868** [comment]
Thank you for your reply.
I  executed these commands:
conda create -n kplex-pool python=3.7 -y
conda activate kplex-pool
conda install -y -c nvidia -c rapidsai -c numba -c conda-forge -c defaults \
      dask-cudf dask-cuda cugraph=0.15 cudatoolkit=10.1 c-compiler cxx-compiler
pip install -r requirements.txt
pip install .

The output of the last command is the following.

Processing /home/waqar/Downloads/kplex-pool-master
  DEPRECATION: A future pip version will change local packages to be built in-place without first copying to a temporary directory. We recommend you use --use-feature=in-tree-build to test your packages with this new behavior before it becomes the default.
   pip 21.3 will remove support for this functionality. You can find discussion regarding this at https://github.com/pypa/pip/issues/7555.
Requirement already satisfied: numpy in /home/waqar/anaconda3/envs/kplex-pool/lib/python3.7/site-packages (from kplex-pool==0.0.1) (1.19.5)
Requirement already satisfied: torch in /home/waqar/anaconda3/envs/kplex-pool/lib/python3.7/site-packages (from kplex-pool==0.0.1) (1.7.0+cu101)
Requirement already satisfied: torch_cluster in /home/waqar/anaconda3/envs/kplex-pool/lib/python3.7/site-packages (from kplex-pool==0.0.1) (1.5.9)
Requirement already satisfied: torch_sparse in /home/waqar/anaconda3/envs/kplex-pool/lib/python3.7/site-packages (from kplex-pool==0.0.1) (0.6.9)
Requirement already satisfied: torch_geometric in /home/waqar/anaconda3/envs/kplex-pool/lib/python3.7/site-packages (from kplex-pool==0.0.1) (2.0.4)
Requirement already satisfied: tqdm in /home/waqar/anaconda3/envs/kplex-pool/lib/python3.7/site-packages (from kplex-pool==0.0.1) (4.64.0)
Requirement already satisfied: dataclasses in /home/waqar/anaconda3/envs/kplex-pool/lib/python3.7/site-packages (from torch->kplex-pool==0.0.1) (0.6)
Requirement already satisfied: typing-extensions in /home/waqar/anaconda3/envs/kplex-pool/lib/python3.7/site-packages (from torch->kplex-pool==0.0.1) (4.2.0)
Requirement already satisfied: future in /home/waqar/anaconda3/envs/kplex-pool/lib/python3.7/site-packages (from torch->kplex-pool==0.0.1) (0.18.2)
Requirement already satisfied: jinja2 in /home/waqar/anaconda3/envs/kplex-pool/lib/python3.7/site-packages (from torch_geometric->kplex-pool==0.0.1) (3.1.1)
Requirement already satisfied: requests in /home/waqar/anaconda3/envs/kplex-pool/lib/python3.7/site-packages (from torch_geometric->kplex-pool==0.0.1) (2.27.1)
Requirement already satisfied: scipy in /home/waqar/anaconda3/envs/kplex-pool/lib/python3.7/site-packages (from torch_geometric->kplex-pool==0.0.1) (1.7.3)
Requirement already satisfied: pandas in /home/waqar/anaconda3/envs/kplex-pool/lib/python3.7/site-packages (from torch_geometric->kplex-pool==0.0.1) (1.1.5)
Requirement already satisfied: scikit-learn in /home/waqar/anaconda3/envs/kplex-pool/lib/python3.7/site-packages (from torch_geometric->kplex-pool==0.0.1) (1.0.2)
Requirement already satisfied: pyparsing in /home/waqar/anaconda3/envs/kplex-pool/lib/python3.7/site-packages (from torch_geometric->kplex-pool==0.0.1) (3.0.8)
Requirement already satisfied: MarkupSafe>=2.0 in /home/waqar/anaconda3/envs/kplex-pool/lib/python3.7/site-packages (from jinja2->torch_geometric->kplex-pool==0.0.1) (2.0.1)
Requirement already satisfied: python-dateutil>=2.7.3 in /home/waqar/anaconda3/envs/kplex-pool/lib/python3.7/site-packages (from pandas->torch_geometric->kplex-pool==0.0.1) (2.8.2)
Requirement already satisfied: pytz>=2017.2 in /home/waqar/anaconda3/envs/kplex-pool/lib/python3.7/site-packages (from pandas->torch_geometric->kplex-pool==0.0.1) (2022.1)
Requirement already satisfied: six>=1.5 in /home/waqar/anaconda3/envs/kplex-pool/lib/python3.7/site-packages (from python-dateutil>=2.7.3->pandas->torch_geometric->kplex-pool==0.0.1) (1.16.0)
Requirement already satisfied: idna<4,>=2.5 in /home/waqar/anaconda3/envs/kplex-pool/lib/python3.7/site-packages (from requests->torch_geometric->kplex-pool==0.0.1) (3.3)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/waqar/anaconda3/envs/kplex-pool/lib/python3.7/site-packages (from requests->torch_geometric->kplex-pool==0.0.1) (1.26.9)
Requirement already satisfied: charset-normalizer~=2.0.0 in /home/waqar/anaconda3/envs/kplex-pool/lib/python3.7/site-packages (from requests->torch_geometric->kplex-pool==0.0.1) (2.0.12)
Requirement already satisfied: certifi>=2017.4.17 in /home/waqar/anaconda3/envs/kplex-pool/lib/python3.7/site-packages (from requests->torch_geometric->kplex-pool==0.0.1) (2021.10.8)
Requirement already satisfied: threadpoolctl>=2.0.0 in /home/waqar/anaconda3/envs/kplex-pool/lib/python3.7/site-packages (from scikit-learn->torch_geometric->kplex-pool==0.0.1) (3.1.0)
Requirement already satisfied: joblib>=0.11 in /home/waqar/anaconda3/envs/kplex-pool/lib/python3.7/site-packages (from scikit-learn->torch_geometric->kplex-pool==0.0.1) (1.1.0)
Building wheels for collected packages: kplex-pool
  Building wheel for kplex-pool (setup.py) ... done
  Created wheel for kplex-pool: filename=kplex_pool-0.0.1-cp37-cp37m-linux_x86_64.whl size=332567 sha256=51c5a2f56a133f4ffbb4d63d7442541f4bef67ab9565727696eabc700be63e62
  Stored in directory: /home/waqar/.cache/pip/wheels/76/75/e6/1463f1724ebc90304cc3c541bcf47e1142414fc2c9320e4433
Successfully built kplex-pool
Installing collected packages: kplex-pool
  Attempting uninstall: kplex-pool
    Found existing installation: kplex-pool 0.0.1
    Uninstalling kplex-pool-0.0.1:
      Successfully uninstalled kplex-pool-0.0.1
Successfully installed kplex-pool-0.0.1

After that, I executed this command: python setup.py test to execute the test suite
The output of this command is given below.

home/waqar/anaconda3/envs/kplex-pool/lib/python3.7/site-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  /pytorch/c10/cuda/CUDAFunctions.cpp:100.)
  return torch._C._cuda_getDeviceCount() > 0
No CUDA runtime is found, using CUDA_HOME='/home/waqar/anaconda3/envs/kplex-pool'
/home/waqar/anaconda3/envs/kplex-pool/lib/python3.7/site-packages/setuptools/dist.py:760: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
  % (opt, underscore_opt)
/home/waqar/anaconda3/envs/kplex-pool/lib/python3.7/site-packages/setuptools/installer.py:30: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
  SetuptoolsDeprecationWarning,
running pytest
/home/waqar/anaconda3/envs/kplex-pool/lib/python3.7/site-packages/setuptools/dist.py:760: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
  % (opt, underscore_opt)
/home/waqar/anaconda3/envs/kplex-pool/lib/python3.7/site-packages/setuptools/command/easy_install.py:147: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  EasyInstallDeprecationWarning,
/home/waqar/anaconda3/envs/kplex-pool/lib/python3.7/site-packages/setuptools/command/install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  setuptools.SetuptoolsDeprecationWarning,
Searching for pytest-cov
Best match: pytest-cov 3.0.0
Processing pytest_cov-3.0.0-py3.7.egg

Using /home/waqar/Downloads/kplex-pool-master/.eggs/pytest_cov-3.0.0-py3.7.egg
Searching for pytest
Best match: pytest 7.1.2
Processing pytest-7.1.2-py3.7.egg

Using /home/waqar/Downloads/kplex-pool-master/.eggs/pytest-7.1.2-py3.7.egg
Searching for coverage[toml]>=5.2.1
Best match: coverage 6.3.2
Processing coverage-6.3.2-py3.7-linux-x86_64.egg

Using /home/waqar/Downloads/kplex-pool-master/.eggs/coverage-6.3.2-py3.7-linux-x86_64.egg
Searching for tomli>=1.0.0
Best match: tomli 2.0.1
Processing tomli-2.0.1-py3.7.egg

Using /home/waqar/Downloads/kplex-pool-master/.eggs/tomli-2.0.1-py3.7.egg
Searching for py>=1.8.2
Best match: py 1.11.0
Processing py-1.11.0-py3.7.egg

Using /home/waqar/Downloads/kplex-pool-master/.eggs/py-1.11.0-py3.7.egg
Searching for pluggy<2.0,>=0.12
Best match: pluggy 1.0.0
Processing pluggy-1.0.0-py3.7.egg

Using /home/waqar/Downloads/kplex-pool-master/.eggs/pluggy-1.0.0-py3.7.egg
Searching for iniconfig
Best match: iniconfig 1.1.1
Processing iniconfig-1.1.1-py3.7.egg

Using /home/waqar/Downloads/kplex-pool-master/.eggs/iniconfig-1.1.1-py3.7.egg
running egg_info
writing kplex_pool.egg-info/PKG-INFO
writing dependency_links to kplex_pool.egg-info/dependency_links.txt
writing requirements to kplex_pool.egg-info/requires.txt
writing top-level names to kplex_pool.egg-info/top_level.txt
/home/waqar/anaconda3/envs/kplex-pool/lib/python3.7/site-packages/torch/utils/cpp_extension.py:339: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
  warnings.warn(msg.format('we could not find ninja.'))
reading manifest file 'kplex_pool.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*' under directory 'cuda'
adding license file 'LICENSE'
writing manifest file 'kplex_pool.egg-info/SOURCES.txt'
running build_ext
copying build/lib.linux-x86_64-3.7/kplex_pool/kplex_cpu.cpython-37m-x86_64-linux-gnu.so -> kplex_pool
copying build/lib.linux-x86_64-3.7/kplex_pool/pool_edges_cpu.cpython-37m-x86_64-linux-gnu.so -> kplex_pool
copying build/lib.linux-x86_64-3.7/kplex_pool/cc_cpu.cpython-37m-x86_64-linux-gnu.so -> kplex_pool
copying build/lib.linux-x86_64-3.7/kplex_pool/simplify_cpu.cpython-37m-x86_64-linux-gnu.so -> kplex_pool
=========================================================================================== test session starts ===========================================================================================
platform linux -- Python 3.7.13, pytest-7.1.2, pluggy-1.0.0 -- /home/waqar/anaconda3/envs/kplex-pool/bin/python
cachedir: .pytest_cache
rootdir: /home/waqar/Downloads/kplex-pool-master, configfile: setup.cfg
plugins: cov-3.0.0
collected 4 items / 2 errors                                                                                                                                                                              

================================================================================================= ERRORS ==================================================================================================
___________________________________________________________________________________ ERROR collecting test/test_kplex.py ___________________________________________________________________________________
ImportError while importing test module '/home/waqar/Downloads/kplex-pool-master/test/test_kplex.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../anaconda3/envs/kplex-pool/lib/python3.7/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
test/test_kplex.py:4: in <module>
    from kplex_pool import KPlexCover
kplex_pool/__init__.py:1: in <module>
    from .kplex import KPlexCover, CliqueCover
kplex_pool/kplex.py:12: in <module>
    import networkx as nx
E   ModuleNotFoundError: No module named 'networkx'
___________________________________________________________________________________ ERROR collecting test/test_pool.py ____________________________________________________________________________________
ImportError while importing test module '/home/waqar/Downloads/kplex-pool-master/test/test_pool.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../anaconda3/envs/kplex-pool/lib/python3.7/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
test/test_pool.py:5: in <module>
    from kplex_pool import KPlexCover
kplex_pool/__init__.py:1: in <module>
    from .kplex import KPlexCover, CliqueCover
kplex_pool/kplex.py:12: in <module>
    import networkx as nx
E   ModuleNotFoundError: No module named 'networkx'

---------- coverage: platform linux, python 3.7.13-final-0 -----------
Name                                                                 Stmts   Miss  Cover
----------------------------------------------------------------------------------------
.eggs/pluggy-1.0.0-py3.7.egg/pluggy/_callers.py                         40     10    75%
.eggs/pluggy-1.0.0-py3.7.egg/pluggy/_hooks.py                          156     92    41%
.eggs/pluggy-1.0.0-py3.7.egg/pluggy/_manager.py                        189    145    23%
.eggs/pluggy-1.0.0-py3.7.egg/pluggy/_result.py                          28     22    21%
.eggs/pluggy-1.0.0-py3.7.egg/pluggy/_tracing.py                         41     31    24%
.eggs/py-1.11.0-py3.7.egg/py/_error.py                                  52     50     4%
.eggs/py-1.11.0-py3.7.egg/py/_path/local.py                            693    688     1%
.eggs/py-1.11.0-py3.7.egg/py/_vendored_packages/apipkg/__init__.py     154    143     7%
.eggs/pytest-7.1.2-py3.7.egg/_pytest/_argcomplete.py                    37     36     3%
.eggs/pytest-7.1.2-py3.7.egg/_pytest/_code/code.py                     714    484    32%
.eggs/pytest-7.1.2-py3.7.egg/_pytest/_code/source.py                   145     90    38%
.eggs/pytest-7.1.2-py3.7.egg/_pytest/_io/terminalwriter.py             119     62    48%
.eggs/pytest-7.1.2-py3.7.egg/_pytest/_io/wcwidth.py                     25     22    12%
.eggs/pytest-7.1.2-py3.7.egg/_pytest/assertion/__init__.py              86     82     5%
.eggs/pytest-7.1.2-py3.7.egg/_pytest/assertion/rewrite.py              632    549    13%
.eggs/pytest-7.1.2-py3.7.egg/_pytest/cacheprovider.py                  312    262    16%
.eggs/pytest-7.1.2-py3.7.egg/_pytest/capture.py                        548    517     6%
.eggs/pytest-7.1.2-py3.7.egg/_pytest/compat.py                         158    127    20%
.eggs/pytest-7.1.2-py3.7.egg/_pytest/config/__init__.py                836    717    14%
.eggs/pytest-7.1.2-py3.7.egg/_pytest/config/argparsing.py              258    213    17%
.eggs/pytest-7.1.2-py3.7.egg/_pytest/config/compat.py                   37     19    49%
.eggs/pytest-7.1.2-py3.7.egg/_pytest/debugging.py                      226    217     4%
.eggs/pytest-7.1.2-py3.7.egg/_pytest/deprecated.py                      21     20     5%
.eggs/pytest-7.1.2-py3.7.egg/_pytest/doctest.py                        352    344     2%
.eggs/pytest-7.1.2-py3.7.egg/_pytest/faulthandler.py                    58     47    19%
.eggs/pytest-7.1.2-py3.7.egg/_pytest/fixtures.py                       812    628    23%
.eggs/pytest-7.1.2-py3.7.egg/_pytest/helpconfig.py                     131    121     8%
.eggs/pytest-7.1.2-py3.7.egg/_pytest/junitxml.py                       368    366     1%
.eggs/pytest-7.1.2-py3.7.egg/_pytest/legacypath.py                     211    183    13%
.eggs/pytest-7.1.2-py3.7.egg/_pytest/logging.py                        395    310    22%
.eggs/pytest-7.1.2-py3.7.egg/_pytest/main.py                           467    301    36%
.eggs/pytest-7.1.2-py3.7.egg/_pytest/mark/__init__.py                  125    110    12%
.eggs/pytest-7.1.2-py3.7.egg/_pytest/mark/structures.py                259    190    27%
.eggs/pytest-7.1.2-py3.7.egg/_pytest/monkeypatch.py                    166    152     8%
.eggs/pytest-7.1.2-py3.7.egg/_pytest/nodes.py                          332    225    32%
.eggs/pytest-7.1.2-py3.7.egg/_pytest/pastebin.py                        70     69     1%
.eggs/pytest-7.1.2-py3.7.egg/_pytest/pathlib.py                        378    310    18%
.eggs/pytest-7.1.2-py3.7.egg/_pytest/python.py                         881    606    31%
.eggs/pytest-7.1.2-py3.7.egg/_pytest/python_path.py                     16     15     6%
.eggs/pytest-7.1.2-py3.7.egg/_pytest/reports.py                        291    281     3%
.eggs/pytest-7.1.2-py3.7.egg/_pytest/runner.py                         287    232    19%
.eggs/pytest-7.1.2-py3.7.egg/_pytest/scope.py                           39     29    26%
.eggs/pytest-7.1.2-py3.7.egg/_pytest/setuponly.py                       58     56     3%
.eggs/pytest-7.1.2-py3.7.egg/_pytest/setupplan.py                       24     22     8%
.eggs/pytest-7.1.2-py3.7.egg/_pytest/skipping.py                       160    156     2%
.eggs/pytest-7.1.2-py3.7.egg/_pytest/stash.py                           36     31    14%
.eggs/pytest-7.1.2-py3.7.egg/_pytest/stepwise.py                        70     68     3%
.eggs/pytest-7.1.2-py3.7.egg/_pytest/terminal.py                       886    734    17%
.eggs/pytest-7.1.2-py3.7.egg/_pytest/tmpdir.py                         100     89    11%
.eggs/pytest-7.1.2-py3.7.egg/_pytest/unittest.py                       246    240     2%
.eggs/pytest-7.1.2-py3.7.egg/_pytest/warnings.py                        74     58    22%
.eggs/pytest-7.1.2-py3.7.egg/pytest/__init__.py                         82     80     2%
.eggs/pytest_cov-3.0.0-py3.7.egg/pytest_cov/compat.py                   19     15    21%
.eggs/pytest_cov-3.0.0-py3.7.egg/pytest_cov/engine.py                  221    200    10%
.eggs/pytest_cov-3.0.0-py3.7.egg/pytest_cov/plugin.py                  214    200     7%
kplex_pool/__init__.py                                                   6      5    17%
kplex_pool/data.py                                                     109     78    28%
kplex_pool/kplex.py                                                    162    153     6%
kplex_pool/pool.py                                                      45     38    16%
kplex_pool/simplify.py                                                  25     22    12%
kplex_pool/utils.py                                                     64     52    19%
test/__init__.py                                                         0      0   100%
test/test_kplex.py                                                      24     20    17%
test/test_pool.py                                                       62     57     8%
test/test_simplify.py                                                   35     25    29%
----------------------------------------------------------------------------------------
TOTAL                                                                13867  11516    17%

========================================================================================= short test summary info =========================================================================================
ERROR test/test_kplex.py
ERROR test/test_pool.py
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 2 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
============================================================================================ 2 errors in 4.51s ===========================================================================================

**Comment by flandolfi** [comment]
Yes, the error log says it cannot find `networkx`, I think I forgot to put it in `requirements.txt`. Run `pip install networkx` in the conda environment and rerun the tests

**Comment by waqar12868** [comment]
Hi,  
After installation of networkx, the setup.py file executes successfully in the Ubuntu terminal. Sorry for again bothering you. When I run the setup.py file in spyder I am getting problems with the Cuda version. 
please look at the error. Please guide me about it if you faced this type of error. 
Thanks.

runfile('/home/waqar/Downloads/kplex-pool-master/setup.py', wdir='/home/waqar/Downloads/kplex-pool-master')
No CUDA runtime is found, using CUDA_HOME='/home/waqar/anaconda3/envs/kplex-pool'
/home/waqar/anaconda3/envs/kplex-pool/lib/python3.7/site-packages/setuptools/dist.py:760: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
  % (opt, underscore_opt)
/home/waqar/anaconda3/envs/kplex-pool/lib/python3.7/site-packages/setuptools/installer.py:30: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
  SetuptoolsDeprecationWarning,
An exception has occurred, use %tb to see the full traceback.

Traceback (most recent call last):

  File "/home/waqar/anaconda3/envs/kplex-pool/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 135, in setup
    ok = dist.parse_command_line()

  File "/home/waqar/anaconda3/envs/kplex-pool/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 502, in parse_command_line
    raise DistutilsArgError("no commands supplied")

DistutilsArgError: no commands supplied


During handling of the above exception, another exception occurred:

SystemExit: usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: no commands supplied

**Comment by flandolfi** [comment]
It's not a problem with CUDA, the error is written in the log and is the same as before:
```
SystemExit: usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
or: setup.py --help [cmd1 cmd2 ...]
or: setup.py --help-commands
or: setup.py cmd --help

error: no commands supplied
```
You're running `setup.py <CMD>` with no command (e.g., `install`/`test`/etc). But I don't know why you're running `setup.py` in the first place, since you already installed `kplex-pool` using `pip install .`, which calls `setup.py install`.

**Comment by waqar12868** [comment]
I got your point. Actually, I want to see the results of your kplex pooling, but I don't know which file will generate the results. So please tell me which file I should run to get results on your model and other pooling models (diffpool, etc.)

**Comment by flandolfi** [comment]
It's written in the README, e.g.,
```
python -m benchmark.eval \
    --dense \
    --lr 0.001 \
    --epochs 100 \
    --hidden 128 \
    --model CoverPool \
    --dataset ENZYMES \
    --k_step_factor 0.5 \
    --node_pool_op add max
```

Notice that to get the results in the paper you have to run the whole grid search with `python -m benchmark.cv <...>`, which may took very long and many resources. Try working with the parameters of `python -m benchmark.eval` instead, you should see some results anyway!

P.S.: `Coverpool` = `KPlexPool`.

**Comment by waqar12868** [comment]
Thank you for your guidance. If I need your help in future, then I will contact you again.

**Comment by flandolfi** [comment]
Actually, I'm about to archive the repo. This is an old piece of junk I can't manage to work on again. The README is self-explainatory, if you want to see the actual use cases have a look at the code (I suggest looking in `benchmark/models.py`), but good luck with that, it's mostly spaghetti-code.

Have a nice day!
